// Generated by gencpp from file object_tracking/DetectedObjectMsg.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKING_MESSAGE_DETECTEDOBJECTMSG_H
#define OBJECT_TRACKING_MESSAGE_DETECTEDOBJECTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <visualization_msgs/MarkerArray.h>
#include <jsk_recognition_msgs/BoundingBoxArray.h>

namespace object_tracking
{
template <class ContainerAllocator>
struct DetectedObjectMsg_
{
  typedef DetectedObjectMsg_<ContainerAllocator> Type;

  DetectedObjectMsg_()
    : markers()
    , boxes()  {
    }
  DetectedObjectMsg_(const ContainerAllocator& _alloc)
    : markers(_alloc)
    , boxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::visualization_msgs::MarkerArray_<ContainerAllocator>  _markers_type;
  _markers_type markers;

   typedef  ::jsk_recognition_msgs::BoundingBoxArray_<ContainerAllocator>  _boxes_type;
  _boxes_type boxes;





  typedef boost::shared_ptr< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObjectMsg_

typedef ::object_tracking::DetectedObjectMsg_<std::allocator<void> > DetectedObjectMsg;

typedef boost::shared_ptr< ::object_tracking::DetectedObjectMsg > DetectedObjectMsgPtr;
typedef boost::shared_ptr< ::object_tracking::DetectedObjectMsg const> DetectedObjectMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_tracking::DetectedObjectMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_tracking::DetectedObjectMsg_<ContainerAllocator1> & lhs, const ::object_tracking::DetectedObjectMsg_<ContainerAllocator2> & rhs)
{
  return lhs.markers == rhs.markers &&
    lhs.boxes == rhs.boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_tracking::DetectedObjectMsg_<ContainerAllocator1> & lhs, const ::object_tracking::DetectedObjectMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0ee17136c14b2823c04c42625441d79";
  }

  static const char* value(const ::object_tracking::DetectedObjectMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0ee17136c14b282ULL;
  static const uint64_t static_value2 = 0x3c04c42625441d79ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_tracking/DetectedObjectMsg";
  }

  static const char* value(const ::object_tracking::DetectedObjectMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visualization_msgs/MarkerArray markers\n"
"jsk_recognition_msgs/BoundingBoxArray boxes\n"
"================================================================================\n"
"MSG: visualization_msgs/MarkerArray\n"
"Marker[] markers\n"
"\n"
"================================================================================\n"
"MSG: visualization_msgs/Marker\n"
"# See http://www.ros.org/wiki/rviz/DisplayTypes/Marker and http://www.ros.org/wiki/rviz/Tutorials/Markers%3A%20Basic%20Shapes for more information on using this message with rviz\n"
"\n"
"uint8 ARROW=0\n"
"uint8 CUBE=1\n"
"uint8 SPHERE=2\n"
"uint8 CYLINDER=3\n"
"uint8 LINE_STRIP=4\n"
"uint8 LINE_LIST=5\n"
"uint8 CUBE_LIST=6\n"
"uint8 SPHERE_LIST=7\n"
"uint8 POINTS=8\n"
"uint8 TEXT_VIEW_FACING=9\n"
"uint8 MESH_RESOURCE=10\n"
"uint8 TRIANGLE_LIST=11\n"
"\n"
"uint8 ADD=0\n"
"uint8 MODIFY=0\n"
"uint8 DELETE=2\n"
"uint8 DELETEALL=3\n"
"\n"
"Header header                        # header for time/frame information\n"
"string ns                            # Namespace to place this object in... used in conjunction with id to create a unique name for the object\n"
"int32 id 		                         # object ID useful in conjunction with the namespace for manipulating and deleting the object later\n"
"int32 type 		                       # Type of object\n"
"int32 action 	                       # 0 add/modify an object, 1 (deprecated), 2 deletes an object, 3 deletes all objects\n"
"geometry_msgs/Pose pose                 # Pose of the object\n"
"geometry_msgs/Vector3 scale             # Scale of the object 1,1,1 means default (usually 1 meter square)\n"
"std_msgs/ColorRGBA color             # Color [0.0-1.0]\n"
"duration lifetime                    # How long the object should last before being automatically deleted.  0 means forever\n"
"bool frame_locked                    # If this marker should be frame-locked, i.e. retransformed into its frame every timestep\n"
"\n"
"#Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...)\n"
"geometry_msgs/Point[] points\n"
"#Only used if the type specified has some use for them (eg. POINTS, LINE_STRIP, ...)\n"
"#number of colors must either be 0 or equal to the number of points\n"
"#NOTE: alpha is not yet used\n"
"std_msgs/ColorRGBA[] colors\n"
"\n"
"# NOTE: only used for text markers\n"
"string text\n"
"\n"
"# NOTE: only used for MESH_RESOURCE markers\n"
"string mesh_resource\n"
"bool mesh_use_embedded_materials\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: std_msgs/ColorRGBA\n"
"float32 r\n"
"float32 g\n"
"float32 b\n"
"float32 a\n"
"\n"
"================================================================================\n"
"MSG: jsk_recognition_msgs/BoundingBoxArray\n"
"# BoundingBoxArray is a list of BoundingBox.\n"
"# You can use jsk_rviz_plugins to visualize BoungingBoxArray on rviz.\n"
"Header header\n"
"BoundingBox[] boxes\n"
"\n"
"================================================================================\n"
"MSG: jsk_recognition_msgs/BoundingBox\n"
"# BoundingBox represents a oriented bounding box.\n"
"Header header\n"
"geometry_msgs/Pose pose\n"
"geometry_msgs/Vector3 dimensions  # size of bounding box (x, y, z)\n"
"# You can use this field to hold value such as likelihood\n"
"float32 value\n"
"uint32 label\n"
;
  }

  static const char* value(const ::object_tracking::DetectedObjectMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.markers);
      stream.next(m.boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObjectMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_tracking::DetectedObjectMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_tracking::DetectedObjectMsg_<ContainerAllocator>& v)
  {
    s << indent << "markers: ";
    s << std::endl;
    Printer< ::visualization_msgs::MarkerArray_<ContainerAllocator> >::stream(s, indent + "  ", v.markers);
    s << indent << "boxes: ";
    s << std::endl;
    Printer< ::jsk_recognition_msgs::BoundingBoxArray_<ContainerAllocator> >::stream(s, indent + "  ", v.boxes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_TRACKING_MESSAGE_DETECTEDOBJECTMSG_H
